#!/bin/bash

D="$1" # dificultad de la clave
nKey="$2"
pssw="$3"

#----------------------------------------------------------------#
invalid="Opción no válida. Por favor, seleccione un tipo de cifrado válido (1-4)."

# dificultad de la clave (bits)
d1=1024
d2=2048
d3=4096
d4=8192

# tipos de cifrado
t1="rsa"
t2="dsa"
t3="ecdsa"
t4="ed25519"

case $D in
    1) D=$d1;; 2) D=$d2;; 3) D=$d3;; 4) D=$d4;;
    *)  echo $invalid;
        exit 1 ;;
esac

# Generar clave SSH con contraseña y nombre personalizado
echo -e "$pssw\n$pssw" | ssh-keygen -t $t1 -b $D -N "" -f "$nKey"
